### PR TITLE
Replace atob/btoa with client B64 to handle unicode strings

### PR DESCRIPTION
**Pull request by elv-zenia**
App was failing at atob(JSON.stringify(jobs)) with error `Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`
This change set implements ~~webtoolkit~~ client utils encoding/decoding for a maintable solution that works with UTF-8 strings.

### CODE REVIEW

**Comment by elv-zenia** [comment]
Relates to #32

**Comment by elv-kevin** [comment]
elv-client-js has a method for this in its utils, it uses the node Buffer type (polyfilled in web). I think this is better than having bespoke code, as long as it handles this case correctly (I would be surprised if it didnt)

https://github.com/eluv-io/elv-client-js/blob/develop/src/Utils.js#L436

**Comment by elv-zenia** [comment]
Nice, will try this out.

**Comment by elv-zenia** [comment]
@elv-kevin Updated. Thanks, that works perfectly.

**Comment by elv-kevin** [comment]
cool, lgtm

**Pull request merged**
